# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
#Token 29df838d44251f43a50febf5ae30a6136eac6911
development:
  secret_key_base: e240f527906566c2804b1cfc5b14f8d7bf4786d66ffdea04fcc46c5608b13b7d1133a729d34cd593b609e34bdac963a841c03e34d0c12cb5128b406136fa3a3b
  github_access_token: "29df838d44251f43a50febf5ae30a6136eac6911"
test:
  secret_key_base: e240f527906566c2804b1cfc5b14f8d7bf4786d66ffdea04fcc46c5608b13b7d1133a729d34cd593b609e34bdac963a841c03e34d0c12cb5128b406136fa3a3b
  github_access_token: <%= ENV["GITHUB_ACCESS_TOKEN"] %>
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  github_access_token: <%= ENV["GITHUB_ACCESS_TOKEN"] %>